### ISSUE TITLE
Could not find a  configuration file provided by "Zephyr-sdk"

### ISSUE THREAD

**Issue by amigomcu** [golioth/zephyr-training#15]
hi ,golioth
Excuse me, I followed the setup to build the sample code, but it seems that some parameters are not configured correctly. How can I handle this issue? i build in WSL2.

(.venv) steven@LAPTOP-436CQ9L1:~/zephyr-training/app$ west build -b nrf7002dk_nrf5340_cpuapp 01_IOT
-- west build: generating a build system
Loading Zephyr default modules (Zephyr base (cached)).
-- Application: /home/steven/zephyr-training/app/01_IOT
-- Cache files will be written to: /home/steven/.cache/zephyr
-- Zephyr version: 3.2.99 (/home/steven/zephyr-training/deps/zephyr)
-- Found west (found suitable version "1.1.0", minimum required is "0.7.1")
-- Board: nrf7002dk_nrf5340_cpuapp
CMake Error at /home/steven/zephyr-training/deps/zephyr/cmake/modules/FindZephyr-sdk.cmake:63 (find_package):
  Could not find a package configuration file provided by "Zephyr-sdk"
  (requested version 0.15) with any of the following names:

    Zephyr-sdkConfig.cmake
    zephyr-sdk-config.cmake

  Add the installation prefix of "Zephyr-sdk" to CMAKE_PREFIX_PATH or set
  "Zephyr-sdk_DIR" to a directory containing one of the above files.  If
  "Zephyr-sdk" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  /home/steven/zephyr-training/deps/zephyr/cmake/modules/FindHostTools.cmake:53 (find_package)
  /home/steven/zephyr-training/deps/zephyr/cmake/modules/dts.cmake:8 (find_package)
  /home/steven/zephyr-training/deps/zephyr/cmake/modules/zephyr_default.cmake:108 (include)
  /home/steven/zephyr-training/deps/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)
  /home/steven/zephyr-training/deps/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:97 (include_boilerplate)
  CMakeLists.txt:5 (find_package)

-- Configuring incomplete, errors occurred!
FATAL ERROR: command exited with status 1: /usr/bin/cmake -DWEST_PYTHON=/home/steven/zephyr-training/.venv/bin/python3 -B/home/steven/zephyr-training/app/build -GNinja -S/home/steven/zephyr-training/app/01_IOT
(.venv) steven@LAPTOP-436CQ9L1:~/zephyr-training/app$

**Comment by szczys** [comment]
Have you installed the Zephyr SDK?

https://docs.zephyrproject.org/latest/develop/toolchains/zephyr_sdk.html
